os: linux
dist: focal
language: c

install:
  - pip install cpplint

addons:
  apt:
    packages:
      - cmake
      - valgrind
      - lcov
      - cppcheck

env:
  - BUILD=Debug
  - BUILD=Release

jobs:
  include:
    - stage: u-tests
      name: "Unit-tests"
      script:
        - cmake -B build -DCMAKE_BUILD_TYPE=$BUILD -DWITH_TESTS=ON
        - make -C build
        - cd build/lib/test/
        - ./u_test_dynamic
        - ./u_test_static

    - stage: TestCoverage
      name: "Test coverage dynamic library"
      script:
        - cmake -B build -DCMAKE_BUILD_TYPE=$BUILD -DWITH_COVERAGE=1
        - make -C build
        - cd build/lib/test/
        - ./u_test_dynamic
        - cd CMakeFiles/u_test_dynamic.dir/src
        - gcov unit_tests_parallel.cpp.gcno
        - lcov --capture --directory ../../ --output-file unit_tests.info
        - genhtml -o ../../../../../../coverage-report unit_tests.info

    - stage: Sanitaize
      name: "Tests for libraries with sanitaize"
      script:
        - cmake -B build -DCMAKE_BUILD_TYPE=$BUILD -DWITH_SANITIZERS=1
        - make -C build
        - cd build/lib/test/
        - ./u_test_dynamic
        - ./u_test_static
        - touch result.txt
        - ./stress_test_d ../../../../files/100mb.txt 3 announced disapperared discreetly
        - ./stress_test_s ../../../../files/100mb.txt 3 announced disapperared discreetly
        - ./stress_test_controller

    - stage: memcheck
      name: "Memory check"
      script:
        - cmake -B build -DCMAKE_BUILD_TYPE=$BUILD -DWITH_TESTS=ON
        - make -C build
        - cd build/lib/test/
        - valgrind --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no ./u_test_dynamic
        - valgrind --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no ./u_test_static
        - touch result.txt
        - valgrind --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no ./stress_test_s ../../../../files/100mb.txt 3 announced disapperared discreetly
        - valgrind --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no ./stress_test_d ../../../../files/100mb.txt 3 announced disapperared discreetly
        - valgrind --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no ./stress_test_controller

    - stage: static_analysis
      name: "Static analysis"
      script:
        - cppcheck --enable=all --error-exitcode=1 --inconclusive lib/* src/*

