language: c

addons:
  apt:
    packages:
      - cmake
      - valgrind
      - lcov

before_script:
  - mkdir cmake-build-debug
  - cd cmake-build-debug
  - cmake ..
  - make

jobs:
  include:
    - stage: tests
      name: "Check tests"
      script:
        - cd src/test
        - ./test

    - stage: coverage
      name: "Test coverage"
      script:
        - cd src/test
        - ./test
        - cd CMakeFiles/test.dir
        - gcov test.cpp.gcno
        - lcov --capture --directory ../../ --output-file tests.info
        - genhtml -o ../../../../coverage-report tests.info
        - cd ../../../../

    - stage: memcheck
      name: "Memory check"
      script:
        - cd src/test
        - valgrind --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no ./test

    - stage: static_analysis
      name: "Static analysis"
      script:
        - cd ..
        - cppcheck --enable=all --error-exitcode=1 --inconclusive src/*

    - stage: linters
      name: "Linters"
      script:
        - cpplint --extensions=cc src/lib/* src/prog/* src/test/*
        - cpplint --extensions=c++ src/test/*